["start", "başlat, başlatmak"],
["create", "oluştur, oluşturmak"],
["left", "sol"],
["right", "sağ"],
["top", "üst"],
["bottom", "alt"],
["width", "genişlik"],
["height", "yükseklik"],
["pixel (px)", "piksel, görüntü elemanı"],
["text", "metin"],
["color", "renk"],
["page", "sayfa"],
["label", "etiket"],
["text box", "metin kutusu"],
["title", "başlık"],
["button", "buton, düğme"],
["image", "görüntü, resim"],
["box", "kutu"],
["on", "üzerinde, üstünde, esnasında"],
["change", "değiştir, değiştirmek"],
["changed", "değişti"],
["click", "tıkla, tıklamak"],
["clicked", "tıklandı"],
["on click", "tıklama esnasında"],
["load", "yükle, yüklemek"],
["loaded", "yüklendi"],
["loading", "yükleniyor"],
["loop", "döngü"],
["print", "yazdır, yazdırmak"],
["function", "fonksiyon, işlev"],
["visible", "görünür, görülebilen"],
["border", "sınır, kenar"],
["round", "yuvarlak"],
["rotate", "döndür, döndürmek"],
["opacity", "şeffaf olmayış, saydam olmayış"],
["align", "hizalamak"],
["aline", "dizilmek"],
["center", "merkez, orta"],
["font", "yazı tipi"],
["size", "boyut, büyüklük"],
["delete", "sil, silmek"],
["deleted", "silindi"],
["if", "eğer, ise"],
["else", "başka, yoksa, aksi halde"],
["break", "kır, kırmak"],
["random", "rasgele"],
["background", "arka plan"],
["new", "yeni"],
["add", "ekle, eklemek"],
["event", "olay, durum"],
["listen", "dinle, dinlemek"],
["listener", "dinleyici"],
["set", "ayarlamak"],
["get", "almak, elde etmek"],
["my", "benim"],
["shape", "şekil"],
["variable (var)", "değişken"],
["string (str)", "metin tipinde değişken, karakter dizisi"],
["number (num)", "numara, ondalıklı sayı tipinde değişken"],
["integer (int)", "tam sayı, tam sayı tipinde değişken"],
["array", "dizi"],
["object", "nesne"],
["object-based", "nesne tabanlı"],
["that", "o, şu"],
["default", "varsayılan"],
["white", "beyaz"],
["gray, grey", "gri"],
["black", "siyah"],
["red", "kırmızı"],
["green", "yeşil"],
["blue", "mavi"],
["orange", "turuncu, portakal"],
["yellow", "sarı"],
["pink", "pembe"],
["purple", "mor"],
["brown", "kahverengi"],
["dark", "koyu, karanlık"],
["light", "ışık, aydınlık, hafif, açık"],
["darkblue", "koyu mavi, lacivert"],
["lightblue", "açık mavi"],
["transparent", "şeffaf"],
["zero", "sıfır"],
["one", "bir"],
["two", "iki"],
["three", "üç"],
["four", "dört"],
["five", "beş"],
["six", "altı"],
["seven", "yedi"],
["eight", "sekiz"],
["nine", "dokuz"],
["ten", "on"],
["clock", "saat"],
["wall clock", "duvar saati"],
["hour", "saat"],
["one hour", "bir saatlik zaman birimi"],
["minutes", "dakika"],
["second", "saniye"],
["time", "zaman, süre"],
["timer", "zamanlayıcı"]